### ISSUE TITLE
Q2 and Q7: looking for clarifications

### ISSUE THREAD

**Issue by yzchang** [eXascaleInfolab/TSM-Bench#45]
For `<sfilter>` in Q2, the code used to generate a `> 0.95` statement for each sensor, but that code is now commented out and it only generates one filter statement on the first sensor.

For Q7, it's the other way around.  Its definition in the VLDB paper is `WHERE st_id = st_k`, but the code generates a list of `id_station == 'st_x' or id_station == 'st_y' or id_station == 'st_z' ...`.

These differences don't change the essence of the queries, but I'd just like to know which definition I should use when generating my own queries for the benchmark (will explain in our Zoom meeting).

**Comment by AbdelouahabKhelifati** [comment]
For Q2:
The decision to perform filtering on only one sensor is intentional to ensure that the size of the output aligns with our target of approximately 5% of the total data. Applying the > 0.95 conditions to multiple sensors would lead to an empty output as the query would be too selective, prompting us to select many sensors but apply the filter on a single sensor for practical output sizing.

For Q7:
In the paper queries Q6 and Q7 were set to target one station and we only varied the time for these queries. This was based on our observation that the results did not vary significantly from previous queries. The code allows nonetheless the execution of this query for more stations if desired.
